-- 코드를 입력하세요
SELECT DISTINCT II.FLAVOR
FROM FIRST_HALF as FH
LEFT JOIN ICECREAM_INFO as II
ON FH.FLAVOR = II.FLAVOR
WHERE FH.TOTAL_ORDER > 3000 and II.INGREDIENT_TYPE LIKE 'fruit_based'
ORDER BY FH.TOTAL_ORDER DESC
