-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE, REST_REVIEW
WHERE MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID AND REST_REVIEW.MEMBER_ID =
(SELECT MEMBER_ID FROM REST_REVIEW
                  GROUP BY MEMBER_ID
                  ORDER BY COUNT(*) DESC 
                  LIMIT 1)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC