-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as GB JOIN USED_GOODS_USER as GU on
GB.WRITER_ID = GU.USER_ID and GB.STATUS = 'DONE'
GROUP BY USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;