-- 코드를 입력하세요
SELECT DISTINCT(CC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR as CC JOIN 
CAR_RENTAL_COMPANY_RENTAL_HISTORY as RH on CC.CAR_ID = RH.CAR_ID
WHERE CC.CAR_TYPE = '세단' and MONTH(START_DATE) = 10
ORDER BY CC.CAR_ID DESC;