-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) as TOTAL_SALES
FROM BOOK JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
and YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 1
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY